module.exports = {

    URL:'http://localhost:3001',
    GET_TASK_PENDING: 'GET_TASK_PENDING',
    GET_TASK_COMPLETED: 'GET_TASK_COMPLETED',
    POST_TASK : 'POST_TASK',
    PUT_TASK : 'PUT_TASK',
    GET_USER: 'GET_USER',
    POST_USER: 'POST_USER',
    PUT_USER: 'PUT_USER',
}